apiVersion: v1
kind: ReplicationController
metadata:
name: tomcat
spec:
replicas: 1
selector:
app: enefro
template:
metadata:
labels:
app: enefro
spec:
containers:
- name: tomcat
image: enefro-tomcat
ports:
- containerPort: 8080
